# Optional browser smoke test: python3 tests/sdd-browser.py [demo-url]
# Requires Playwright and an installed Chromium. SDD_CHROMIUM can override its path.
import os
import sys
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
url = sys.argv[1] if len(sys.argv) > 1 else 'http://127.0.0.1:4000/cs3300_m26/demos/sdd-workbench/'
launch_options = {"headless": True}
if os.environ.get('SDD_CHROMIUM'):
    launch_options['executable_path'] = os.environ['SDD_CHROMIUM']
def screenshot(page, name):
    if os.environ.get('SDD_SCREENSHOTS'):
        folder = Path(os.environ['SDD_SCREENSHOTS'])
        folder.mkdir(parents=True, exist_ok=True)
        page.screenshot(path=str(folder / name), full_page=True)
with sync_playwright() as p:
    browser = p.chromium.launch(**launch_options)
    page = browser.new_page(viewport={"width":1440,"height":1100}, device_scale_factor=1)
    errors = []
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.goto(url)
    expect(page.locator('#sdd-status')).to_contain_text('8 attribute equations')
    page.locator('#sdd-next').click()
    expect(page.locator('#sdd-count')).to_have_text('1 / 8 equations')
    page.locator('#sdd-finish').click()
    expect(page.locator('#sdd-result-note')).to_have_text('Root AST: -(x, *(2, y))')
    screenshot(page, 'sdd-desktop.png')
    page.locator('[data-preset=inherited]').click()
    page.locator('#sdd-finish').click()
    expect(page.locator('#sdd-result-note')).to_have_text('Root AST: -(-(x, *(2, y)), z)')
    page.locator('#sdd-prev').click()
    expect(page.locator('#sdd-count')).to_have_text('21 / 22 equations')
    page.locator('#sdd-tree [data-node="1"]').click()
    expect(page.locator('#sdd-node-detail')).to_contain_text('n1')
    page.locator('[data-preset=arithmetic]').click()
    expect(page.locator('#sdd-run')).to_be_disabled()
    page.locator('#sdd-finish').click()
    page.locator('#sdd-run').click()
    expect(page.locator('#sdd-run-status')).to_contain_text('Result: 4')
    page.locator('[data-preset=boolean]').click()
    root_bounds = page.locator('#sdd-tree [data-node="0"]').bounding_box()
    tree_bounds = page.locator('#sdd-tree').bounding_box()
    assert tree_bounds['x'] <= root_bounds['x'] <= tree_bounds['x'] + tree_bounds['width'] - root_bounds['width']
    page.locator('#sdd-finish').click()
    page.locator('#sdd-run').click()
    expect(page.locator('#sdd-run-status')).to_contain_text('Result: true')
    assert page.locator('.sdd-runtime-code .is-skipped').count() == 9
    page.locator('#sdd-env').fill('x=250, y=250')
    page.locator('#sdd-run').click()
    expect(page.locator('#sdd-run-status')).to_contain_text('Result: false')
    page.locator('#sdd-input').fill('x <')
    expect(page.locator('#sdd-workspace')).to_be_hidden()
    page.locator('#sdd-form button').click()
    expect(page.locator('#sdd-status')).to_contain_text('Cannot parse')
    page.locator('[data-preset=ast]').click()
    page.locator('#sdd-rule-editor > summary').click()
    page.locator('#sdd-source').fill('S -> id\n self.node = self.node')
    page.locator('#sdd-input').fill('x')
    page.locator('#sdd-form button').click()
    expect(page.locator('#sdd-status')).to_contain_text('Cyclic')
    page.locator('#sdd-source').fill('S -> id\n self.node = Leaf("<script>alert(1)</script>")')
    page.locator('#sdd-form button').click()
    page.locator('#sdd-finish').click()
    assert page.locator('#sdd-result script').count() == 0
    expect(page.locator('#sdd-result-note')).to_contain_text('<script>alert(1)</script>')
    page.locator('#sdd-restore').click()
    page.locator('#sdd-rule-editor > summary').click()
    page.locator('#sdd-play').click()
    page.wait_for_timeout(1000)
    page.locator('#sdd-play').click()
    assert page.locator('#sdd-count').inner_text() != '0 / 8 equations'
    page.set_viewport_size({"width":390,"height":844})
    screenshot(page, 'sdd-mobile.png')
    assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth')
    page.set_viewport_size({"width":1440,"height":1100})
    page.locator('[data-preset=program]').click()
    expect(page.locator('#sdd-program-options')).to_be_visible()
    expect(page.locator('#sdd-input')).to_have_attribute('rows','13')
    expect(page.locator('#sdd-result-title')).to_have_text('Generated IR')
    expect(page.locator('#sdd-run')).to_be_enabled()
    page.locator('#sdd-result [data-instruction="0"]').click()
    expect(page.locator('#sdd-source-preview .is-current')).to_contain_text('i = 1;')
    expect(page.locator('#sdd-dependencies')).to_contain_text('copy(id.lexeme, E.addr)')
    screenshot(page, 'sdd-program-desktop.png')
    page.locator('#sdd-run').click()
    expect(page.locator('#sdd-run-status')).to_contain_text('Program finished')
    expect(page.locator('#sdd-run-output')).to_have_text('65')
    expect(page.locator('#sdd-run-values')).to_contain_text('total = 65')
    page.locator('#sdd-run-first').click()
    expect(page.locator('#sdd-run-values')).to_have_text('(no variables assigned)')
    page.locator('#sdd-run-next').click()
    expect(page.locator('#sdd-run-values')).to_have_text('i = 1')
    page.locator('#sdd-replay').click()
    expect(page.locator('#sdd-count')).to_contain_text('0 /')
    expect(page.locator('#sdd-run')).to_be_disabled()
    page.locator('#sdd-finish').click()
    page.locator('#sdd-example').select_option('guarded')
    page.locator('#sdd-load-example').click()
    page.locator('#sdd-run').click()
    expect(page.locator('#sdd-run-output')).to_have_text('-1')
    page.locator('#sdd-input').fill('x=2; print(x/0);')
    page.locator('#sdd-form button').click()
    page.locator('#sdd-run').click()
    expect(page.locator('#sdd-run-status')).to_contain_text('by zero')
    expect(page.locator('#sdd-run-values')).to_contain_text('x = 2')
    page.locator('#sdd-example').select_option('nested')
    page.locator('#sdd-load-example').click()
    page.locator('#sdd-run').click()
    expect(page.locator('#sdd-run-output')).to_have_text('25')
    page.set_viewport_size({"width":390,"height":844})
    screenshot(page, 'sdd-program-mobile.png')
    assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth')
    page.reload()
    expect(page.locator('#sdd-input-label')).to_have_text('Source program')
    assert not errors, errors
    print('Browser checks passed: all presets, stepping, playback, editing, diagnostics, execution, escaping, and mobile overflow.')
    browser.close()
